### ISSUE TITLE
Feature: User-can-search-a-place 

### ISSUE THREAD

**Issue by lindsay-jin** [lindsay-jin/study-spot-finder#1]
## ⚙️ Feature

User can search for a place to study. User can search via several options, including location, keyword, and radius. User can also choose how many listings they want to see from the search, how they would like the search listings to be sorted and choose to only display places that are open now. 

## 🖼️ Wireframes

https://www.figma.com/file/r2WCPDiKYPdw1bkZl05b8L/Lindsay-Jin--Front-End-Project?type=design&node-id=3%3A9237&mode=design&t=Xia59URwYZICueEj-1

## ✅ Task List

- [x] Create HTML elements for each input used to search for a place
- [x] Create HTML elements for the name, address and a container for the photo to be displayed
- [x] Query the DOM for each element
- [x] Add an event listener to the the search button
- [x] Use fetch and data from inputs to get the corresponding search result
- [x] Update the text content of the name and address
- [x] Use the fsq_id from the fetch result to fetch the URL of the photo of the place
- [x] Update the src of the image with the URL to display in the search result
