### ISSUE TITLE
Feature: User-can-like-a-listing 

### ISSUE THREAD

**Issue by lindsay-jin** [lindsay-jin/study-spot-finder#2]
## ⚙️ Feature

User can like a listing, which will then be added to the favorites page.

## 🖼️ Wireframes

https://www.figma.com/file/r2WCPDiKYPdw1bkZl05b8L/Lindsay-Jin--Front-End-Project?type=design&node-id=3%3A9237&mode=design&t=Xia59URwYZICueEj-1

## ✅ Task List

- [ ] User can click on the photo of a listing which opens a page with more details on the listing
- [ ] Define a function called viewSwap that hides and shows pages
- [ ] Create HTML and CSS for the details page
- [ ] Add event listener on photos of listings
- [ ] Add event listener on the heart icon, when clicked, the listing gets added to the favorites page
- [ ] Add a property called likedEntries to the Data interface
- [ ] Add a function that updates likedEntries when user likes a listing
- [ ] Create HTML and CSS for the favorites page
- [ ] Add event listener to the icons on the navigation bar on the bottom, viewSwap on click
