### ISSUE TITLE
Feature: User-can-delete-a-favorite

### ISSUE THREAD

**Issue by lindsay-jin** [lindsay-jin/study-spot-finder#3]
## ⚙️ Feature

User can delete a listing from the favorites page by unliking a listing. 

## 🖼️ Wireframes

https://www.figma.com/file/r2WCPDiKYPdw1bkZl05b8L/Lindsay-Jin--Front-End-Project?type=design&node-id=3%3A9237&mode=design&t=Xia59URwYZICueEj-1

## ✅ Task List

- [ ] Update the click event listener on listing, when solid heart is clicked again and becomes empty
     - [ ] Update the data.likedEntries and remove that listing from the data.likedEntries
- [ ] If removing a listing results in an empty favorites list, display a message indicating that the favorites list is empty.
