### ISSUE TITLE
Feature: User-can-edit-a-listing

### ISSUE THREAD

**Issue by lindsay-jin** [lindsay-jin/study-spot-finder#4]
## ⚙️ Feature

User can add additional information to a listing that are provided in the prompt. Such as is there wifi, are the seats comfortable, etc. 

## 🖼️ Wireframes

https://www.figma.com/file/r2WCPDiKYPdw1bkZl05b8L/Lindsay-Jin--Front-End-Project?type=design&node-id=3%3A9237&mode=design&t=Xia59URwYZICueEj-1

## ✅ Task List

- [x] Add event listener to edit button on details page
     - [x] remove disabled attribute from select so user can choose options
 - [x] when user edit a listing, the new listing is saved as an object in data.editedEntries
 - [x] when user clicks save, check if the listing(name) already exist in the data.likedEntries
     - [x] if it does, replace the old one with new object
     - [x] if it doesn’t exist in data.likedEntires, add it to data.likedEntries
 - [x]  when user clicks a listing, check if the listing(name) is in data.editedEntries
     - [x] if it is, render the details page with the object in data.editedEntries
     - [x] If not, render the details with basic info
